### ISSUE TITLE
Creating the Firebase Project

### ISSUE THREAD

**Issue by bryantto08** [4human-org/murphy-ecommerce-backend#3]
We need to make the firebase project.

**Comment by Connor-Skudlarek** [comment]
I am going to get this done in 2 days.

**Comment by Calesi19** [comment]
I'm gonna need the emails of those who will have access to the firebase project.

**Comment by Calesi19** [comment]
![Screenshot 2024-02-14 at 9 54 48 PM](https://github.com/4human-org/murphy-ecommerce-backend/assets/58052598/b9f6cd46-15bf-4f65-b933-6e9e1c68e113)

Firebase project was created and it is ready with the free plan. Some members have already been invited.

**Comment by Connor-Skudlarek** [comment]
This issue was completed a while ago. Closing.
